### ISSUE TITLE
  requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url:

### ISSUE THREAD

**Issue by Coax88** [paulmacnicol/openai_vision#1]
Hi

I get his error when running the shell command

```
stdout: ""
stderr: >-
  Traceback (most recent call last):
    File "/config/custom_components/openai_vision/image2text.py", line 206, in <module>
      main()
    File "/config/custom_components/openai_vision/image2text.py", line 186, in main
      response = get_response(image_path, args.model, combined_text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/config/custom_components/openai_vision/image2text.py", line 86, in get_response
      response.raise_for_status()
    File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url:
  https://api.openai.com/v1/chat/completions
returncode: 1
```
**this is the https url in the error message**

```
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

**this is my settings**

```
settings:
  HA_URL: "http://192.168.1.241:8123"
  RESPONSE_DIR: "/config/custom_components/openai_vision/responses"
  MEDIA_DIR: "/config/custom_components/openai_vision/responses"
  HASS_TOKEN: "xxxxxxxxxxxxxxxxxxxxxxx1M2U2NjI5ZDc0MDM4NiIsImlhdCI6MTcxNzY1MDM1OCwiZXhwIjoyMDMzMDEwMzU4fQ.nz4fH9A9h5Ab4KVGbISQGdloQnlDRlzseMe2gsq9jPU"
  OPENAI_API_KEY: "sk-proj-AaxpV3xxxxxxxxxxxxxxxxxuBoZKfFbHLSLdSqvHr9e"
  MODEL_CHOICES:
    - gpt-3.5-turbo
    - gpt-4
    - gpt-4o
    - gpt4-turbo
    - gpt-3.5-turbo-16k
```

**config.yaml**

```
openai_vision:
  sensors:
    - name: Weather

shell_command:
  run_openai_weather: "python3 /config/custom_components/openai_vision/image2text.py --camera camera.camera_2 --prompt Weather --style BBC --model gpt-4"
```

**Comment by paulmacnicol** [comment]
Ive done some testing, and only the following 3 models are available for image upload via the API:

    - gpt-4o
    - gpt-4-turbo
    - gpt-4-1106-vision-preview

I've removed the invalid options, please pull the project again and choose one of these options
